---
title: "Presentations"
---

**20\.** **Stratton, C.** July 2026. "Listening for disease: integrating acoustic and disease surveillance data to assess impacts of White-nose Syndrome on bats." Invited talk given during an Inspire Session at the Ecological Society of America Conference. Salt Lake City, UT, USA. \vspace*{2mm}

**19\.** **Stratton, C.** July 2026. "Learning from Messy Data: the Benefits of Student-Collected Data in the Classroom." Contributed oral presentation given at the International Conference on Teaching Statistics. Brisbane, Queensland, AUS. \vspace*{2mm}

**18\.** **Stratton, C.** and A. Hoegh. July 2026. "Learning from Messy Data: the Benefits of Student-Collected Data in the Classroom." Contributed oral presentation given at the International Conference on Teaching Statistics. Brisbane, Queensland, AUS. \vspace*{2mm}

**17\.** **Stratton, C.** November 2025. "Statistical methodology for radio-telemetry data with connections to partial differential equations." Research presentation given to the Emerging Mathematics and Statistics Research Group. Middlebury, VT, USA. \vspace*{2mm}

**16\.** **Stratton, C.**, K.M. Irvine, K.M. Banner, E. Almberg, D. Bachen, and K. Smucker. October 2025. "A statistical assessment of the impact of White-nose Syndrome on bats in Montana." Research presentation given at Fall Faculty Forum. Middlebury, VT, USA. \vspace*{2mm}

**15\.** **Stratton, C.**, K.M. Irvine, K.M. Banner, E. Almberg, D. Bachen, and K. Smucker. June 2025. "Joint spatial modeling of bat activity and disease with computational considerations." Invited talk given at the Western North American Region of the International Biometric Society conference. Whistler, BC, CAN. \vspace*{2mm}

**14\.** **Stratton, C.**, K.M. Irvine, K.M. Banner, E. Almberg, D. Bachen, and K. Smucker. June 2025. "Joint spatial modeling of bat activity and disease with computational considerations." Invited talk given at the Western North American Region of the International Biometric Society conference. Whistler, BC, CAN. \vspace*{2mm}

**13\.** **Stratton, C.** April 2025. "Gaussian processes and Bayesian computation." Research presentation given to the Emerging Mathematics and Statistics Research Group. Middlebury, VT, USA. \vspace*{2mm}

**12\.** **Stratton, C.** October 2024. "Joint spatial models, Bayesian statistics, and MCMC estimation." Research presentation given to the Emerging Mathematics and Statistics Research Group. Middlebury, VT, USA. \vspace*{2mm}

**11\.** **Stratton, C.**, K.M. Irvine, K.M. Banner, E. Almberg, D. Bachen, and K. Smucker. September 2023. "Joint spatial modeling bridges the gap between disparate disease surveillance and population monitoring efforts informing conservation of at-risk bat species" Invited talk given at the MT Chapter of the ASA annual meeting. Bozeman, MT, USA. 

**10\.** **Stratton, C.**, K.M. Irvine, K.M. Banner, E. Almberg, D. Bachen, and K. Smucker. "Joint spatial modeling of ecological response and disease processes improves estimator precision." 2023. Talk given at the Joint Statistical Meetings. Toronto, Ontario, Canada.

**9\.** **Stratton, C.**, K.M. Irvine, K.M. Banner, E. Almberg, D. Bachen, and K. Smucker. "A statistical framework for integrating White-nose syndrome surveillance data and acoustic population monitoring data."2023. Talk given to the U.S. Geological Survey Disease Coordination Group. Virtual.

**8\.** **Stratton, C.**, K.M. Irvine, K.M. Banner, E. Almberg, D. Bachen, and K. Smucker. "Leveraging WNS surveillance and NABat data improves estimation of disease spread and bat activity." 2023. Poster presented at the Whitenose Syndrome National Meeting. Palm Springs, California, USA.

**7\.** **Stratton, C.**, K.M. Irvine, E. Almberg, K. Smucker, and J. Gude. "Joint spatial modeling of relative activity and disease processes." 2022. Poster presented at the ENVR 2022 Workshop: Environmental and Ecological Statistical Research and Applications with Societal Impacts. Provo, Utah, USA.

**6\.** **Stratton, C.**, K.M. Irvine, E. Almberg, K. Smucker, and J. Gude. "Bats & Stats: Assessing Impacts of White-nose Syndrome on Western Bat Species." 2022. Talk given at the Northern Rocky Mountain Science Center. Bozeman, Montana, USA.

**5\.** **Stratton, C.**, A. Hoegh, K.M. Irvine, K.M. Banner. 2021. "Clustering and ordination with Dirichlet process mixture models." Invited talk given at the Joint Statistical Meetings. Virtual.

**4\.** **Stratton, C.**, J.L. Green. 2021. "Beyond normal: Understanding power through `R` Shiny." Poster presented at the United States Conference on Teaching Statistics. Virtual.

**3\.** **Stratton, C.**, A. Hoegh, and J.L. Green. 2018. "Predicting pitch type: A case study in Bayesian hierarchical multinomial regression." Invited talk given at the Joint Statistical Meetings. Vancouver, Canada.

**2\.** **Stratton, C.**, A. Hoegh, and J.L. Green. 2018. "Unraveling Kershaw's dominance." Poster presented at The Cascadia Symposium on Statistics in Sports. Vancouver, Canada.

**1\.** **Stratton, C.** and J.L. Green. 2018. "The power of technology: A Shiny applet assisted approach to teaching statistical power." Poster presented at the Electronic Conference on Teaching Statistics. Virtual.
